### ISSUE TITLE
Qwen2 Models

### ISSUE THREAD

**Issue by ChuanhongLi** [abhibambhaniya/GenZ-LLM-Analyzer#2]
Excellent work!  

Does genz support Qwen2 series, such as Qwen2-7B-Instruct (https://huggingface.co/Qwen/Qwen2-7B-Instruct)? 
I am a little confused about how to set the parameters, such as num_ffi  for Qwen2-7B-Instruct Model.

```
model_config = ModelConfig(model='Qwen/Qwen2-7B-Instruct',
            hidden_size=3584, num_attention_heads=28, 
            num_key_value_heads=4, num_ffi = ?,
            intermediate_size=18944, num_decoder_layers=28,
            max_model_len=32768, vocab_size=152064,
            )
```
Is this OK? What is the value for num_ffi? 

Thanks for your help!

**Comment by abhibambhaniya** [comment]
Thanks for using GenZ!!

Yes the parameters set for Qwen2 are correct. num_ffi for Qwen2-7B model would be 2. 

Num_ffi is number of (up_proj + gate_proj) in each MLP layer. 

This can be determined by examining [model.safetensors.index.json](https://huggingface.co/Qwen/Qwen2-7B-Instruct/blob/main/model.safetensors.index.json), here since both up_proj and gate_proj is 1, num_ffi = 2.

Hope that clears the confusion, please don't hesitate if you have any more questions.
